import { routes } from "./routes";

export interface Activity {
  title: string;
  des: string;
  level: string;
  age: string;
  duration: string;
  prize: string;
  link: string;
  images: string[];
}

export const activitiesData: Activity[] = [
  {
    title: "Circuito Multiaventura",
    des: "Situamos nuestro Circuito Multiaventura en Venta del Moro - Valencia. Circuito multiaventura totalmente integrado en la naturaleza! Totalmente integrado en la naturaleza, nuestro circuito encaja de forma natural en el paraje que hemos elegido para esta multiactividad tan emocionante. Los retos que tendreis que superar de una forma natural sin torres ni casetas artificiales dan una auténtica sensacion de aventura desplazandonos entre árboles.",
    level: "Medio",
    age: "Desde 6 años",
    duration: "2  Horas",
    prize: "35",
    link: routes.circuitoMultiaventura.path,
    images: ["/api/v1/assets/activity/circito.png"],
  },
  {
    title: "Rafting ",
    des: "AIGUAROCA es la primera empresa de deportes de aventura y eventos de España en completar el abanico de actividades con la nueva y espectacular atraccion.",
    level: "Medio",
    age: "Desde 6 años",
    duration: "2  Horas",
    prize: "40",
    link: routes.rafting.path,
    images: ["/api/v1/assets/activity/rafting.jpg"],
  },
  {
    title: "Rafting Tamayo",
    des: "Tramo Rafting Tamayo.",
    level: "Medio",
    age: "Desde 6 años",
    duration: "2  Horas",
    prize: "40",
    link: routes.raftingTamayo.path,
    images: ["/api/v1/assets/activity/tamayo.png"],
  },
  {
    title: "Rafting Hoces del Cabriel",
    des: "Tramo Rafting Hoces del Cabriel.",
    level: "Avanzado",
    age: "Desde 14 años",
    duration: "4-5 Horas",
    prize: "65",
    link: routes.raftingCabriel.path,
    images: ["/api/v1/assets/activity/cabrial.png"],
  },
  {
    title: "Paintball",
    des: "El paintball es un juego al aire libre en el que contamos con una marcadora (pistola) de bolas de pintura, con la cual deberemos alcanzar a nuestros oponentes. Para desarrollar la actividad iremos completamente equipados, para que sea divertido y totalmente seguro.",
    level: "Principiante",
    age: "Desde 16 años",
    duration: "2  Horas",
    prize: "30",
    link: routes.paintball.path,
    images: ["/api/v1/assets/activity/paintball.png"],
  },
  {
    title: "Kayak en Aguas Bravas",
    des: "El kayak es el deporte de aventura por excelencia en aguas bravas. Una embarcación diseñada para el descenso de ríos de gran caudal, fuertes corrientes y rápidos agresivos, lo que se conoce como aguas bravas y que requiere de experiencia en remo, además de una buena preparación física. Los descensos en kayak por aguas bravas con AIGUAROCA son totalmente seguros, guiados por monitores experimentados que te enseñarán las técnicas para dominar la estabilidad del kayak, trayectorias y maniobras para hacer un descenso divertido y emocionante. Esta actividad se realiza en todos los tramos del Río Cabriel en función de los caudales de cada momento.",
    level: "Medio",
    age: "Desde 14 años",
    duration: "2  Horas",
    prize: "40",
    link: routes.kayakAguasBravas.path,
    images: ["/api/v1/assets/activity/bravas.png"],
  },
  {
    title: "Kayak Travesia",
    des: "Como actividad de relax. Anti-estrés, calma pero muy divertida, os proponemos el kayak en aguas tranquilas, en el Embalse de Contreras con embarcaciones semirígidas individuales.",
    level: "Principiante",
    age: "Desde 6 años",
    duration: "2  Horas",
    prize: "35",
    link: routes.kayakTravesia.path,
    images: ["/api/v1/assets/activity/kayak.png"],
  },
  {
    title: "Canoa-Raft",
    des: "Canoas de dos plazas diseñadas específicamente para descensos en ríos de aguas bravas. Son bastante estables como para poder descender tramos de cierta dificulta con total garantía de sentir grandes emociones y vivir una aventura inolvidable. Para ello los dos participantes tendrán que sincronizar sus acciones a la hora de palear, teniendo que desarrollar un buen trabajo en equipo. Nuestros descensos son siempre acompañados y guiados por monitores expertos que controlan en todo momento e instruyen a todos los participantes desde sus kayaks.",
    level: "Principiante",
    age: "Desde 6 años",
    duration: "2  Horas",
    prize: "40",
    link: routes.canoas.path,
    images: ["/api/v1/assets/activity/canoa.png"],
  },
  {
    title: "Barranco Acuático",
    des: "Este tipo de barrancos suelen ser alimentados por regímenes de agua nivales, siendo en la época de deshielo cuando alcanzan los máximos niveles de caudal. El primer equipamiento que necesitaremos será un traje de neopreno que mantenga la temperatura de nuestro cuerpo, ya que pasaremos bastante tiempo en el agua. Para superar las dificultades y desniveles que encontraremos en nuestro descenso utilizaremos también técnicas de escalada y espeleología así como material especÃ­fico para barrancos. Se encuentra en la cabecera del rio Cabriel. Nos ofrece un recorrido lleno de saltos a pozas y varios toboganes que tendremos que saltar para superar los siguientes retos. Si el nivel de agua es bueno, lo que suele suceder casi todo el año, se puede descender sin la utilización de cuerdas. Esta circunstancia lo convierte en ideal para la iniciaciÃ³n del barranquismo. Además de la aventura que supone superar los saltos y toboganes, podremos disfrutar de la increíble formación geológica que esconde en su interior, donde encontraremos hasta algún tronco fosilizado.",
    level: "Medio",
    age: "Desde 10 años",
    duration: "3  Horas",
    prize: "45",
    link: routes.barrancoAcuatico.path,
    images: ["/api/v1/assets/activity/barranco.png"],
  },
];

export const allActivitiesData: Activity[] = [
  {
    title: "Rafting en Tamayo-Venta del Moro",
    des: "Los descensos en Rafting que ofrecemos en Venta del Moro son ideales para los que siempre han deseado subirse a una barca de Rafting, para los que buscan Rafting en Valencia o actividades Multiaventura cerca de Valencia o en la Comunidad Valenciana, para viajes familiares, para excursiones de estudiantes, equipos deportivos, empresas, una gran fiesta de cumpleaños o una despedida de solteros multiaventura.",
    level: "Medio",
    age: "Desde 6 años",
    duration: "2  Horas",
    prize: "40",
    link: routes.raftingTamayo.path,
    images: ["/api/v1/assets/activity/tamayo.png"],
  },
  {
    title: "Rafting en Las Hoces del Cabriel - Venta del Moro",
    des: "Sin duda el tramo de Las Hoces del Cabriel es el mejor sitio para hacer Rafting en Valencia En la época de apertura de la presa de Contreras, primavera y verano, se convierte en el caudal idóneo para los deportes de aventura en aguas bravas.",
    level: "Avanzado",
    age: "Desde 14 años",
    duration: "5 Horas",
    prize: "75",
    link: routes.raftingCabriel.path,
    images: ["/api/v1/assets/activity/cabrial.png"],
  },
  {
    title: "Circuito Multiaventura",
    des: "Situamos nuestro Circuito Multiaventura en Venta del Moro - Valencia. Circuito multiaventura totalmente integrado en la naturaleza! Totalmente integrado en la naturaleza, nuestro circuito encaja de forma natural en el paraje que hemos elegido para esta multiactividad tan emocionante. Los retos que tendreis que superar de una forma natural sin torres ni casetas artificiales dan una auténtica sensacion de aventura desplazandonos entre árboles.",
    level: "Medio",
    age: "Desde 6 años",
    duration: "2  Horas",
    prize: "35",
    link: routes.circuitoMultiaventura.path,
    images: ["/api/v1/assets/activity/circito.png"],
  },
  {
    title: "Kayak en Aguas Bravas",
    des: "El kayak es el deporte de aventura por excelencia en aguas bravas. Una embarcación diseñada para el descenso de ríos de gran caudal, fuertes corrientes y rápidos agresivos, lo que se conoce como aguas bravas y que requiere de experiencia en remo, además de una buena preparación física. Los descensos en kayak por aguas bravas con AIGUAROCA son totalmente seguros, guiados por monitores experimentados que te enseñarán las técnicas para dominar la estabilidad del kayak, trayectorias y maniobras para hacer un descenso divertido y emocionante. Esta actividad se realiza en todos los tramos del Río Cabriel en función de los caudales de cada momento.",
    level: "Medio",
    age: "Desde 14 años",
    duration: "2  Horas",
    prize: "40",
    link: routes.kayakAguasBravas.path,
    images: ["/api/v1/assets/activity/bravas.png"],
  },
  {
    title: "Paintball",
    des: "El paintball es un juego al aire libre en el que contamos con una marcadora (pistola) de bolas de pintura, con la cual deberemos alcanzar a nuestros oponentes. Para desarrollar la actividad iremos completamente equipados, para que sea divertido y totalmente seguro.",
    level: "Principiante",
    age: "Desde 16 años",
    duration: "2  Horas",
    prize: "30",
    link: routes.paintball.path,
    images: ["/api/v1/assets/activity/paintball.png"],
  },
  {
    title: "Kayak Travesia",
    des: "Como actividad de relax. Anti-estrés, calma pero muy divertida, os proponemos el kayak en aguas tranquilas, en el Embalse de Contreras con embarcaciones semirígidas individuales.",
    level: "Principiante",
    age: "Desde 6 años",
    duration: "2  Horas",
    prize: "35",
    link: routes.kayakTravesia.path,
    images: ["/api/v1/assets/activity/kayak.png"],
  },
  {
    title: "Canoa-Raft",
    des: "Canoas de dos plazas diseñadas específicamente para descensos en ríos de aguas bravas. Son bastante estables como para poder descender tramos de cierta dificulta con total garantía de sentir grandes emociones y vivir una aventura inolvidable. Para ello los dos participantes tendrán que sincronizar sus acciones a la hora de palear, teniendo que desarrollar un buen trabajo en equipo. Nuestros descensos son siempre acompañados y guiados por monitores expertos que controlan en todo momento e instruyen a todos los participantes desde sus kayaks.",
    level: "Principiante",
    age: "Desde 6 años",
    duration: "2  Horas",
    prize: "40",
    link: routes.canoas.path,
    images: ["/api/v1/assets/activity/canoa.png"],
  },
  {
    title: "Barranco Acuatico",
    des: "Este tipo de barrancos suelen ser alimentados por regímenes de agua nivales, siendo en la época de deshielo cuando alcanzan los máximos niveles de caudal. El primer equipamiento que necesitaremos será un traje de neopreno que mantenga la temperatura de nuestro cuerpo, ya que pasaremos bastante tiempo en el agua. Para superar las dificultades y desniveles que encontraremos en nuestro descenso utilizaremos también técnicas de escalada y espeleología así como material especÃ­fico para barrancos. Se encuentra en la cabecera del rio Cabriel. Nos ofrece un recorrido lleno de saltos a pozas y varios toboganes que tendremos que saltar para superar los siguientes retos. Si el nivel de agua es bueno, lo que suele suceder casi todo el año, se puede descender sin la utilización de cuerdas. Esta circunstancia lo convierte en ideal para la iniciaciÃ³n del barranquismo. Además de la aventura que supone superar los saltos y toboganes, podremos disfrutar de la increíble formación geológica que esconde en su interior, donde encontraremos hasta algún tronco fosilizado.",
    level: "Medio",
    age: "Desde 10 años",
    duration: "3  Horas",
    prize: "45",
    link: routes.barrancoAcuatico.path,
    images: ["/api/v1/assets/activity/barranco.png"],
  },
];
